language: python
sudo: false
python:
- '3.6'
- 3.7-dev
before_install:
- python --version
- uname -a
- lsb_release -a
install:
- pip install tox
script:
- tox -v -e py
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: serhii73
  password:
    secure: aIUaS9ZqNm61hdMkqjWXVa+xcAEqMnNtzicJYy/LxewlEi/T47mxO+MLxnIAfuPQnF8RjcfiCCuAam6ESG0FEf9SwlIk9ZfFaVN1kTMeZIx4jLwJfx6cwH9AqFM6SBW7EeXEXzm7oQkuQtDC/VdaYM1DjhenJPjMS5S5t/Gfa7XwNAcG08PaUACfJw5Z1SnzxDxk0ocM+Soi5u7l9UrH1cSGQAdSw7/6h9dW+cLszis8VIhrqTNVYIKOWSCvoxTmgmr1Xi6YmZq96AHp2Nx9Rtx0TIlb/cPgK58PZ/nEcLQgv572QhdPdHhrtWl+MJZy8RJVUOWuNVbh+3cBDzWMCb2+ttOHZttbddMCaZX6aXDp+PrxamyDSP3F3IdGDGytWgoy951fBhK/0T8zLaRKSCwxna+FCaRnNNkkZV/f+ysjoBMU3PtGdX09q1Uz3If6j6jBcRrah0d9odmNxtMAMw48GfqYt+yhvZh+Wu8Si10KRRe4hfrwYc2lYooREnaRLL4Ha/pzbhGm2ka9/CE4AFNsh5vtrwyfXgFxpHmsLm79knRoZxzAhRBwkMNbPz/mIB6iPCDslEeY5mFVc5fXGHtQUsU6YO7O+PJBDJI0FMmZ4ahbEeIPhMc7FGDWetJWLEvEbXO9F8AeGRqDngnRqLhvElCjggwj5iJeq9Q2BXY=
